### PR TITLE
WIP: select: Fix syntax highlighting with select non-keyword

### LINKED ISSUE #149: "select" in variable name confuses parser
Opening a file which contains a variable with `select` in the name appears to crash/confuse the parser:

image

with variable commented out:
image

### PR DESCRIPTION
**Pull request by kc9jud**
Fixes #149.

### CODE REVIEW

**Comment by kc9jud** [comment]
This may conflict with #157.

**Comment by pedro-ricardo** [comment]
Hello there @kc9jud thank you for the time to look into this, I've found some examples in that your fix fails and the current highlight works.

```fortran
program main

    select type (item => current%item)
    type is (integer)
        !...
    type is (logical)
        !...
    end select

    selecttype (item => current%item)
    typeis (integer)
        !...
    typeis (logical)
        !...
    endselect
  
end program main
```

### This is your modification's output:
Screenshot_2020-02-24_14-04-07
### This is the current highlight:
Screenshot_2020-02-24_14-03-47

The **problem's core** appear to be in the line continuation `&` **not** in the `select` rules.
If a variable is declared in the same line of a declaration statement, the highlight knows that it is a variable, but if it is in another line the problem happens.
Screenshot_2020-02-24_14-16-20 Screenshot_2020-02-24_14-16-42

I suggest you to test this in your code, move the `select_named` variable to the first line of the declaration and let's see if it still happens.

**Comment by pedro-ricardo** [comment]
I think I found it. :+1: 
Please check if the branch in PR #165 fixes your issue. 
It should. If it solves your issue than please close this one.

Also, thanks for reporting and requesting the changes!

**Comment by pedro-ricardo** [comment]
@kc9jud, Let me know if the release branch solver your issue.

**Comment by kc9jud** [comment]
This seems to have fixed my issue. Thanks!

**Pull request closed without merging**
