### PR TITLE
New GNU Fortran intrinsics.

### PR DESCRIPTION
**Pull request by pedro-ricardo**
Added missing intrinsic functions from newest GFortran documentation at [Intrinsic-Procedures](https://gcc.gnu.org/onlinedocs/gfortran/Intrinsic-Procedures.html#Intrinsic-Procedures).
Also Fix issue #113 by adding `ELSE` and `STOP` as keywords
- [x] Add intrinsics on `js` file 
- [x] Add intrinsic `json` files

### CODE REVIEW

**Comment by krvajal** [comment]
We should add the new intrinsics here as well https://github.com/krvajal/vscode-fortran-support/blob/master/src/docs/

**Comment by pedro-ricardo** [comment]
I'll add those soon, thank you.

**Comment by pedro-ricardo** [comment]
Done that tedious work of copying the documentation to `json` files. :+1:

**Comment by pedro-ricardo** [comment]
@krvajal Is that a reason why our intrinsic documentation files have 3 or 4 copies of the same structure?
Like the first one ABORT.json and all others I've oppended, the structure of the file should resemble the below:
```json
{
"keyword":"",
"docstr":""
}
```
But they are in one line and repeated 4 times or more
```json
{"keyword":"","docstr":""}{"keyword":"","docstr":""}{"keyword":"","docstr":""}{"keyword":"","docstr":""}
``` 
If you look for the closing bracket and enter return after each one this is what you'll get
abort

Should we consider this a bug?

**Comment by krvajal** [comment]
> Should we consider this a bug?

Yes, it is indeed a bug as it is not valid JSON.

**Comment by pedro-ricardo** [comment]
Ok done. Used VSCode smart search and replace to remove duplicates and then indent the files better.

**Comment by machsix** [comment]
Maybe we should also add functions for double precision float number like `DABS`, `DSIN`, and etc.?
A list of them can be found at 
https://github.com/vim/vim/blob/master/runtime/syntax/fortran.vim#L146

**Pull request merged**
