### PR TITLE
Bug/nested case select

### LINKED ISSUE #181: inconsistent syntax highlighting for nested case-selects
The Modern Fortran 2 extension by @pedro-ricardo in the VS code appears to have a bug with syntax highlighting which is not present in the main Modern Fortran extension, see `case(2)` colouring in the figure below. Also, the highlighting with the `fortran-language-server` through the extension FORTRAN IntelliSense appears to be partially broken but I will raise this as a separate issue.
image

### PR DESCRIPTION
**Pull request by gnikit**
Fixes #181 .
I tested locally and it works fine although it would be great if we could add some unittests for it to not break again.

### CODE REVIEW

**Comment by gnikit** [comment]
@pedro-ricardo Have you had a chance to look at this? It would be great if we could merge it to master.

**Comment by pedro-ricardo** [comment]
Yes, I've tested it for `select case` and `select type`.
It does solves the nested issue.

**Review by pedro-ricardo — APPROVED** [review]

**Comment by gnikit** [comment]
@krvajal @pedro-ricardo If all is okay then, can I merge or do you want me to add this to CHANGELOG?

**Comment by krvajal** [comment]
Yes please

**Comment by gnikit** [comment]
I have pushed the latest changes to my fork but for some reason GitHub thinks that my fork is based on another repo and not this one. I suspect it rebased my fork when this repo went private. I will try and fix this but in of chance I can't get it to work I will close this PR and open a new one.

**Pull request closed without merging**
