### PR TITLE
[wip] rewrite fortran parser using antlr & modify symbol provider

### PR DESCRIPTION
**Pull request by lcastillov**

### CODE REVIEW

**Comment by pedro-ricardo** [comment]
Why is this change needed? Is there a performance issue I don't know about?

**Comment by lcastillov** [comment]
@pedro-ricardo We are just experimenting with Antlr, nothing is going to change at least we can get a really nice and efficient parser.

**Comment by pedro-ricardo** [comment]
Well I don't know much about Antlr but you need to get those Travis CI tests passing before we try it. Does this modifications you made change highlight or it is only for symbol list?

**Comment by lcastillov** [comment]
@pedro-ricardo Those changes only modify symbol list, in order to fix travis I need to setup Java and install antlr to do the tests. I will fix that later.

**Comment by krvajal** [comment]
@lcastillov any updates on this?

**Pull request closed without merging**
