### PR TITLE
Change default configuration of LanguageServer

### PR DESCRIPTION
**Pull request by pedro-ricardo**
As it is in experimental stage so far, this flag should be **false** by default.
This PR changes the configuration default value for `fortran.useLanguageServer`

### CODE REVIEW

**Comment by pedro-ricardo** [comment]
Travis-CI tests aren't passig ... will take a look at this before merging

**Comment by pedro-ricardo** [comment]
Can't tell what is happening but `npm install ` then `npm run vscode:prepublish` is generating compilation issues:
```

node_modules/vscode-languageclient/lib/client.d.ts:1:707 - error TS2305: Module ''vscode'' has no exported member 'DocumentSymbol'.

1 import { TextDocumentChangeEvent, TextDocument, Disposable, OutputChannel, FileSystemWatcher as VFileSystemWatcher, DiagnosticCollection, Diagnostic as VDiagnostic, Uri, ProviderResult, CancellationToken, Position as VPosition, Location as VLocation, Range as VRange, CompletionItem as VCompletionItem, CompletionList as VCompletionList, SignatureHelp as VSignatureHelp, Definition as VDefinition, DocumentHighlight as VDocumentHighlight, SymbolInformation as VSymbolInformation, CodeActionContext as VCodeActionContext, Command as VCommand, CodeLens as VCodeLens, FormattingOptions as VFormattingOptions, TextEdit as VTextEdit, WorkspaceEdit as VWorkspaceEdit, Hover as VHover, CodeAction as VCodeAction, DocumentSymbol as VDocumentSymbol, DocumentLink as VDocumentLink, TextDocumentWillSaveEvent, WorkspaceFolder as VWorkspaceFolder, CompletionContextas VCompletionContext } from 'vscode';
                                                                  ~~~~~~~~~~~~~~


node_modules/vscode-languageclient/lib/foldingRange.d.ts:1:52 - error TS2305: Module ''vscode'' has no exported member 'FoldingRange'.

1 import { Disposable, TextDocument, ProviderResult, FoldingRange as VFoldingRange, FoldingContext } from 'vscode';
                                                     ~~~~~~~~~~~~


node_modules/vscode-languageclient/lib/foldingRange.d.ts:1:83 - error TS2305: Module ''vscode'' has no exported member 'FoldingContext'.

1 import { Disposable, TextDocument, ProviderResult, FoldingRange as VFoldingRange, FoldingContext } from 'vscode';
                                                                                    ~~~~~~~~~~~~~~


node_modules/vscode-languageclient/lib/protocolConverter.d.ts:54:54 - error TS2694: Namespace ''vscode'' has no exported member 'DocumentSymbol'.

54     asDocumentSymbol(value: ls.DocumentSymbol): code.DocumentSymbol;
                                                        ~~~~~~~~~~~~~~


node_modules/vscode-languageclient/lib/protocolConverter.d.ts:56:57 - error TS2694: Namespace ''vscode'' has no exported member 'DocumentSymbol'.

56     asDocumentSymbols(value: ls.DocumentSymbol[]): code.DocumentSymbol[];
                                                           ~~~~~~~~~~~~~~


node_modules/vscode-languageclient/lib/protocolConverter.d.ts:57:76 - error TS2694: Namespace ''vscode'' has no exported member 'DocumentSymbol'.

57     asDocumentSymbols(value: ls.DocumentSymbol[] | undefined | null): code.DocumentSymbol[] | undefined;
                                                                              ~~~~~~~~~~~~~~


node_modules/vscode-languageclient/lib/protocolConverter.d.ts:93:56 - error TS2694: Namespace ''vscode'' has no exported member 'FoldingRangeKind'.

93     asFoldingRangeKind(kind: string | undefined): code.FoldingRangeKind | undefined;
                                                          ~~~~~~~~~~~~~~~~


node_modules/vscode-languageclient/lib/protocolConverter.d.ts:94:46 - error TS2694: Namespace ''vscode'' has no exported member 'FoldingRange'.

94     asFoldingRange(r: ls.FoldingRange): code.FoldingRange;
                                                ~~~~~~~~~~~~


node_modules/vscode-languageclient/lib/protocolConverter.d.ts:95:61 - error TS2694: Namespace ''vscode'' has no exported member 'FoldingRange'.

95     asFoldingRanges(foldingRanges: ls.FoldingRange[]): code.FoldingRange[];
                                                               ~~~~~~~~~~~~


node_modules/vscode-languageclient/lib/protocolConverter.d.ts:97:80 - error TS2694: Namespace ''vscode'' has no exported member 'FoldingRange'.

97     asFoldingRanges(foldingRanges: ls.FoldingRange[] | undefined | null): code.FoldingRange[] | undefined;
                                                                                  ~~~~~~~~~~~~


node_modules/vscode-languageclient/lib/protocolConverter.d.ts:98:80 - error TS2694: Namespace ''vscode'' has no exported member 'FoldingRange'.

98     asFoldingRanges(foldingRanges: ls.FoldingRange[] | undefined | null): code.FoldingRange[] | undefined;
                                                                                  ~~~~~~~~~~~~
```
in CI and in my pc too. But the errors are not in our files ...

**Comment by pedro-ricardo** [comment]
Looks like we have to update the vscode engine in **package.json** it solves the problem. All tests seems to pass.
Also corrected missing semicolons and wrong '==' statements found by running **npm run lint**

**Comment by pedro-ricardo** [comment]
@krvajal do you agree with the changes? 
Commit [ac442ef](https://github.com/krvajal/vscode-fortran-support/pull/93/commits/ac442efa0f4f88589dcc9edaf8caa660c2ecdb84) is pretty big

**Comment by krvajal** [comment]
Please merge!

**Pull request merged**
