### PR TITLE
Fix select highlight after & operator

### PR DESCRIPTION
**Pull request by pedro-ricardo**
The error reported in #149 was in the `line-continuation-operator` pattern that was missing from both `name-list` and `attribute-list` scopes used in declaration statements.
### Before this change:
Screenshot_2020-02-24_20-42-50
### After this change:
Screenshot_2020-02-24_20-43-29

### CODE REVIEW

**Comment by kc9jud** [comment]
This does not fix #149. Here's a snippet which will cause this to fail:

```
      namelist /inputlist/
     $     Nprotons, Nneutrons, Nshell, fmass, hbomeg,
     $     Nmin, deltaN, Nmax, WTmax, TwoMj, parity, Hrank, NormOrd,
     $     TBMEfile, Trelfile, Hrelfile, Vnnfile,
     $     strTrel, lamHcm, strVnn,
     $     neivals, maxits, startit, selectpiv, tol,
     $     numTBops, obdme, IFLAG_mode, blksize,
     $     uniqueID, orbitalfile, partitioningfile,
     $     DistrDiagTiles, reduce_solver_threads,
     $     checkpoint, write_matrix, observables_only,
     $     initvec_index, initvec_smwffilename
!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
!     Reading input file
      inquire(file='mfdn.input', exist=input)
      if (input) then
         open(unit=inputunit, file='mfdn.input',
     $        status='old', action='read')
         read(inputunit, nml=inputlist)
         close(unit=inputunit, status='keep')
      else
         print*, 'No inputfile...'
         ! call cancelall(000)
         stop
      endif
```

Note, this is *fixed-format* Fortran, not free-format.

**Comment by pedro-ricardo** [comment]
@kc9jud, Thanks for the feedback ... I think that's because you have a different `line-continuation-operator` . I was not especting that `$` there.

**Comment by pedro-ricardo** [comment]
Meh ... More stuff wrong, besides that `$` over there that is confusing me, the `namelist` is just a keyword highlighted it does not behave like a declaration statement

**Comment by pedro-ricardo** [comment]
@kc9jud, I'm not able to transform the `namelist` in a declaration that will recognize and highlight the \groups\  and variables. It should not be difficult tho, I just don't understand the scopes enough to make it.
Therefore I separated the `select-construct` scope into 3 different ones, restricting them a little bit more (similar to what you did before).
This will solve the `select` in variables but will not do anything about that `$` or the `namelist` scope.
Could you check it now?

**Comment by krvajal** [comment]
Is this good enough to be merged @pedro-ricardo? Even it it not cover all the cases it is already an improvement. Or I am missing something?

**Comment by pedro-ricardo** [comment]
Yep, That's basicaly it :+1:

**Pull request merged**
