### PR TITLE
Minor release - version 2.1.2

### LINKED ISSUE #140: Incorrect symbol kind of module subroutines
The symbol kind shown for subroutines in modules should be "function" but currently is "method".  "method" is reserved for usage in classes. In the context of Fortran, "method" should only be used for type-bound procedures (see bottom of http://fortranwiki.org/fortran/show/Object-oriented+programming).

### LINKED ISSUE #148: incorrect bracketing "(//))"
An additional round bracket is inserted. (//) this syntax is used for assigning values for an array.
rec
Is this controlled by this extension?

### LINKED ISSUE #149: "select" in variable name confuses parser
Opening a file which contains a variable with `select` in the name appears to crash/confuse the parser:

image

with variable commented out:
image

### LINKED ISSUE #154: "No symbols found in document" using vscode 1.41.0
When I open a fortran file, it does not show any symbols (function/subroutine) in the "Outline" portion on the left of the gui. This used to work for me but seems to have stopped sometime.

I have also added

```
  "fortran.symbols": ["function", "subroutine"]
```
in my settings.json file.

I am on Mac OSX Catalina with vscode version 1.41.0

### PR DESCRIPTION
**Pull request by pedro-ricardo**
#### Highlight
- [x] `select` keyword - *Merge #165 to fix #149*
- [x] `rank` keyword -  *Merge #165*
#### Symbol List
- [x] Symbols bug in VSCode +1.40 - *Merge #161 to fix #154*
- [x] Symbols classification - *Merge #141 to fix #140*
- [x] Long named symbols - *Merge #151*
#### Settings
- [x] Add more options - *Merge #152*
#### Dependencies
- [x] Merge `dependabot` PR's
    - [x] lodash - *Merge #144*
    - [x] mixin-deep - *Merge #146*
    - [x] handlebars - *Merge #155* 
#### Code Completion
- [x] Array constructor - *Fix #148*
#### New Features
- [ ] Breakpoints - *Merge #150*

### CODE REVIEW

**Comment by krvajal** [comment]
If we merge #150 maybe the version should be 2.2.0 instead, as it is adding a new feature.

**Comment by pedro-ricardo** [comment]
Agreed ! Should we change it here? or separate the #150 Merge to a new PR

**Comment by krvajal** [comment]
Here is fine, but maybe you need to rename the branch

**Comment by pedro-ricardo** [comment]
Hum ... by rename you mean push this to a new branch and delete this one right? I don't know how to simply rename it

**Comment by krvajal** [comment]
Yes, that the only way. You can try this https://gist.github.com/lttlrck/9628955

**Pull request closed without merging**
