### PR TITLE
Implement Go to Definition service

### PR DESCRIPTION
**Pull request by krvajal**
Allow the user to navigate to the definition of a function call defined in the same file or in any other file in the project. The user can use both Go to Definition and Peek Definition functionality.

### CODE REVIEW

**Comment by daloic** [comment]
Would it be possible to integrate with the [Fortran Language Server](https://github.com/hansec/fortran-language-server/)? Combining it with this [simple Fortran extension](https://marketplace.visualstudio.com/items?itemName=Gimly81.fortran) we already have a very robust code navigation and error reporting (like scope masking etc.). It would be great to have all the good stuff of your extension combined with the language server.

**Comment by daloic** [comment]
It is very easy to enable the Fortran Language Server with your extension, just apply [these small patches](https://github.com/hansec/vscode-fortran-ls/issues/3) on the LS extension and add `"onLanguage:fortran_fixed-form"` as activation event in `package.json` for your extension (I also added `.for` as fixed format extension).

**Comment by krvajal** [comment]
This is really nice!! I will love to have this included. I just dont have the time right now to make it happen but you seem to be in the right direction.

**Comment by daloic** [comment]
I will prepare a pull request for you and one for the language server. I will simply reference each other and create a small how-to use them. This will be done early/middle of next week.

**Comment by krvajal** [comment]
Closing this as the suggestion by @daloic seems more attractive.

**Pull request closed without merging**
