### PR TITLE
fea: log error to OutputChannel, suppress warning

### PR DESCRIPTION
**Pull request by machsix**
log error to OutputChannel for easy debug missing headers

### CODE REVIEW

**Comment by gnikit** [comment]
Hi @machsix thanks for the PR, would mind providing some more info about the issue this PR addresses?

**Comment by machsix** [comment]
The PR creates a new log channel for the extension and logs the error message when running gfortran compilation. It is helpful for conditions like gfortran is not installed or some mistake in the environment variable settings.

**Comment by gnikit** [comment]
That is an useful addition instead of failing silently, thanks. Do you have any idea how could we implement a unit test for the log channel?

**Comment by krvajal** [comment]
Thanks for your contribution. I went ahead based on your idea and implemented a bit more generic solution. It is now available on master. I will try to release it this weekend

**Pull request closed without merging**
