### PR TITLE
Release/1.1.0

### PR DESCRIPTION
**Pull request by krvajal**
After merging #47 #46 we can release a new version.
### Release checklist
- [x] Update changelog
- [x] Fix failing CI 
- [x] Merge PRs (#47, #46) into this branch
- [x] Merge into master, tag and release new version

### CODE REVIEW

**Comment by pedro-ricardo** [comment]
@krvajal, still don't know if i got this right but i'm running the extension tests:
```
npm install
npm run vscode:prepublish
npm run lint
npm test --silent
```
And all the tests are **passing**, but the problem seems to be that this command `npm test --silent` never ends ... and that's why Travis-CI can't approve. They have a 10min time limit.

CI log:
> No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.

Still studying how to write this tests

**Comment by krvajal** [comment]
Try to run the tests locally and see if you can identify which one is taking longer than expected. 




Get Outlook







On Sat, Apr 14, 2018 at 4:51 PM +0200, "Pedro Ricardo C Souza" <notifications@github.com> wrote:












@krvajal, still don't know if i got this right but i'm running the extension tests:
npm install
npm run vscode:prepublish
npm run lint
npm test --silent



And all the tests are passing, but the problem seems to be that this command npm test --silent never ends ... and that's why Travis-CI can't approve. They have a 10min time limit.


CI log:



No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.



Still studying how to write this tests

**Comment by pedro-ricardo** [comment]
Not sure if it is a fix ... but returning the `index.ts` file to the original one from VSCode tutorials seems to solve the issue. All tests are performed and passed, and the `npm test` command exits normally. If you consider this a fix i can make a commit so you can see.

**Comment by pedro-ricardo** [comment]
Not sure why, but nether of the highlight changes me and kgerheiser proposed are in the 1.1.0 release in vscode extension. But i can see them when I run the extension through extension host in master branch.

**Comment by krvajal** [comment]
What version of the extension do you have installed? Is it 1.1.0 or 1.1.1

**Comment by vkbo** [comment]
I have 1.1.1 installed.

It currently looks like this:
image

The main issue is that it interprets the endif as a fortran endif, otherwise I'm not particularly concerned with the pre-processor lines not being highlighted.

**Comment by krvajal** [comment]
It was a mistake on my side. I made the release while been on the wrong branch so the changes were not reflected properly. I have published a patched version (1.1.2) that should solve the issue. Please let me know if this is the case.
And please move the discussion to an issue and not as part of the PR.

**Pull request merged**
