### PR TITLE
Minor release for version 1.3.1

### PR DESCRIPTION
**Pull request by pedro-ricardo**
### Check List
- [x] Update changelog
- [x] Merge #79 for fix on function symbol list
- [x] Merge #76 for fix on multiple line dummy argument highlight
- [x] Update Package.json

### CODE REVIEW

**Comment by pedro-ricardo** [comment]
@krvajal Looks good to me. If you need anything else for the release let me know.

**Comment by pedro-ricardo** [comment]
Latest commit updates package version to 1.3.1 .
And corrects a warning from VSCode on file **package.json** in the variables `categories`: https://github.com/krvajal/vscode-fortran-support/blob/1968fc96ff1b20f3570c92f6c8b3c592289f34f6/package.json#L16

> Value is not accepted. Valid values: "Languages", "Snippets", "Linters", "Themes", "Debuggers", "Other", "Keymaps", "Formatters", "Extension Packs", "SCM Providers", "Azure", "Language Packs".

Changed from `Programming Languages` to `Languages`

**Comment by pedro-ricardo** [comment]
That warning was from an older version o VSCode, newer ones use `Programming Languages`. 
Sorry about it.

**Comment by krvajal** [comment]
Amazing work. I will publish the release as soon as possible. In the meantime lets merge this already into master.

**Pull request merged**
