### PR TITLE
Highlight improvements

### PR DESCRIPTION
**Pull request by kgerheiser**
These changes are a complete rewrite of the syntax rules. I took the syntax highlighting from the Atom extension "language-fortran" (https://github.com/dparkins/language-fortran), modified it for use in vscode, and added a couple of other tweaks for correct coloring.

This should fix all of the open issues regarding syntax highlighting, and adds support for many more Fortran features.

I haven't updated or run the built-in tests, but all of my Fortran files highlight flawlessly now even when presented with complicated language features.

Thoughts @pedro-ricardo @krvajal?

### CODE REVIEW

**Comment by pedro-ricardo** [comment]
I'll take a look if it works in my files as well

**Comment by krvajal** [comment]
Does it solves the syntax highlighting issues #40 #34 #38 ?

**Comment by kgerheiser** [comment]
@krvajal
Yes, it does, issues #34-#41 as well as #24 are fixed (aside from the auto-complete issue).

@pedro-ricardo
Ah, I guess there’s an issue with pre-processor directives. I’ll take a look at that.

**Comment by krvajal** [comment]
LGTM

**Pull request merged**
